In [37]:
import numpy as np
import cPickle
data = cPickle.load(open('data.pk', 'rb'))

In [27]:
data

{'test_inputs': array([[182,  89, 186],
        [ 42,  67, 242],
        [ 67, 242,  22],
        ...,
        [141, 108, 176],
        [108, 176,  22],
        [176,  22, 217]], dtype=int32),
 'test_targets': array([143,  22,  54, ...,  22, 217, 191], dtype=int32),
 'train_inputs': array([[ 27,  25,  89],
        [183,  43, 248],
        [182,  31,  75],
        ...,
        [ 43,  58,  75],
        [ 27,  25,  35],
        [ 75, 122, 223]], dtype=int32),
 'train_targets': array([143, 116, 121, ...,  46, 192, 143], dtype=int32),
 'valid_inputs': array([[169, 136, 189],
        [136, 189, 142],
        [189, 142,  58],
        ...,
        [249, 175,  25],
        [175,  25, 248],
        [ 25, 248, 131]], dtype=int32),
 'valid_targets': array([142,  58, 139, ..., 248, 131, 143], dtype=int32),
 'vocab': [u'all',
  u'set',
  u'just',
  u'show',
  u'being',
  u'money',
  u'over',
  u'both',
  u'years',
  u'four',
  u'through',
  u'during',
  u'go',
  u'still',
  u'children',
  u'before',

In [28]:
# a list of the 250 words in the dictionary
data['vocab']

[u'all',
 u'set',
 u'just',
 u'show',
 u'being',
 u'money',
 u'over',
 u'both',
 u'years',
 u'four',
 u'through',
 u'during',
 u'go',
 u'still',
 u'children',
 u'before',
 u'police',
 u'office',
 u'million',
 u'also',
 u'less',
 u'had',
 u',',
 u'including',
 u'should',
 u'to',
 u'only',
 u'going',
 u'under',
 u'has',
 u'might',
 u'do',
 u'them',
 u'good',
 u'around',
 u'get',
 u'very',
 u'big',
 u'dr.',
 u'game',
 u'every',
 u'know',
 u'they',
 u'not',
 u'world',
 u'now',
 u'him',
 u'school',
 u'several',
 u'like',
 u'did',
 u'university',
 u'companies',
 u'these',
 u'she',
 u'team',
 u'found',
 u'where',
 u'right',
 u'says',
 u'people',
 u'house',
 u'national',
 u'some',
 u'back',
 u'see',
 u'street',
 u'are',
 u'year',
 u'home',
 u'best',
 u'out',
 u'even',
 u'what',
 u'said',
 u'for',
 u'federal',
 u'since',
 u'its',
 u'may',
 u'state',
 u'does',
 u'john',
 u'between',
 u'new',
 u';',
 u'three',
 u'public',
 u'?',
 u'be',
 u'we',
 u'after',
 u'business',
 u'never',
 u'use',
 u'here

In [29]:
# the word with index 0
data['vocab'][0]

u'all'

In [35]:
# a 372,500 × 3 matrix where each row gives the indices
# of the 3 context words for one of the 372,500 training cases.
print data['train_inputs'].shape
print data['train_inputs'][0] # accessing the 1st row of the matrix
data['train_inputs']

(372500, 3)
[27 25 89]


array([[ 27,  25,  89],
       [183,  43, 248],
       [182,  31,  75],
       ...,
       [ 43,  58,  75],
       [ 27,  25,  35],
       [ 75, 122, 223]], dtype=int32)

In [31]:
# a vector giving the index of the target word for each training case.
print data['train_targets'].shape
data['train_targets']

(372500,)


array([143, 116, 121, ...,  46, 192, 143], dtype=int32)

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[1, 2]

6